# Generated by Django 4.0.1 on 2022-03-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineenv',
            old_name='config_filename_fk',
            new_name='config_id_fk',
        ),
    ]
