# Generated by Django 4.0.1 on 2022-03-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_rename_config_filename_fk_pipelineenv_config_id_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='config_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.pipelineapp'),
        ),
    ]
