# Generated by Django 4.0.1 on 2022-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_alter_pipelineapp_repo_scan_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_archived',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_private',
            field=models.BooleanField(),
        ),
    ]
