# Generated by Django 4.0.1 on 2022-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_alter_pipelineapp_scm_repo_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineapp',
            name='config_filename',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_default_branch_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_primary_branch_name',
            field=models.CharField(max_length=64),
        ),
    ]
