# Generated by Django 4.0.1 on 2022-03-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_alter_pipelineenv_cf_app_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='cf_app_git_branch',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pipelineenv',
            name='cf_app_git_commit',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pipelineenv',
            name='cf_commit_date',
            field=models.DateTimeField(),
        ),
    ]
