# Generated by Django 4.0.1 on 2022-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_alter_pipelineenv_git_compare_ahead_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='config_env',
            field=models.CharField(max_length=64),
        ),
    ]
