# Generated by Django 4.0.1 on 2022-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_alter_pipelineenv_git_compare_merge_base_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='drift_time_simple',
            field=models.DurationField(),
        ),
    ]
