# Generated by Django 4.0.1 on 2022-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0015_alter_pipelineenv_drift_time_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='drift_time_merge_base',
            field=models.DurationField(),
        ),
    ]
