# Generated by Django 4.0.1 on 2022-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0016_alter_pipelineenv_drift_time_merge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='cf_commit_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pipelineenv',
            name='git_compare_merge_base_commit_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
