# Generated by Django 4.0.1 on 2022-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0020_alter_pipelineenv_cf_commit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineenv',
            name='cf_commit_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineenv',
            name='drift_time_merge_base',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineenv',
            name='drift_time_simple',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineenv',
            name='git_compare_merge_base_commit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
