# Generated by Django 4.0.1 on 2022-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0022_alter_pipelineenv_git_compare_ahead_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_archived',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_private',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
