# Generated by Django 4.0.1 on 2022-04-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0027_alter_pipelineapp_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineapp',
            name='scm_repo_branch_list',
            field=models.TextField(),
        ),
    ]
